apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delete-task-ingress
  # annotations:
  #   kubernetes.io/ingress.class: addon-http-application-routing
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: delete.mahender.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: delete-task
            port: 
              number: 80
