apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msadd-ingress   
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: create.mahender.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: msadd-service
            port: 
              number: 80
