apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-tasks
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: get-tasks
  template:
    metadata:
      labels:
        app: get-tasks
    spec:
      containers:
      - name: get-tasks
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:firstvisionserver.database.windows.net,1433;Database=firstvisiondb;Uid=firstvision;Pwd=pASSWORD@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"                                          
        image: firstvisionresistry.azurecr.io/ms-gettask:v1
        ports:
        - containerPort: 8000
